*: update vendor, ignore some errors in eks delete (#191)
* *: update CHANGELOG, vendor

Signed-off-by: Gyuho Lee <leegyuho@amazon.com>

* eks/conformance: fmt

Signed-off-by: Gyuho Lee <leegyuho@amazon.com>

* eksconfig: ignore/log error in validate config file sync

Signed-off-by: Gyuho Lee <leegyuho@amazon.com>

* pkg/logutil: ignore writer error for log file

Signed-off-by: Gyuho Lee <leegyuho@amazon.com>

* CHANGELOG: update

Signed-off-by: Gyuho Lee <leegyuho@amazon.com>

* eks: ignore more sync errors

Signed-off-by: Gyuho Lee <leegyuho@amazon.com>

* eks: do no fail delete on missing file

Signed-off-by: Gyuho Lee <leegyuho@amazon.com>

* *: fix darwin build with docker dependency

https://github.com/ory/dockertest/issues/212#issuecomment-685167115

=== Building target=aws-k8s-tester, os=darwin ===
github.com/docker/docker/pkg/term
vendor/github.com/docker/docker/pkg/term/tc.go:13:28: undefined: unix.SYS_IOCTL
vendor/github.com/docker/docker/pkg/term/tc.go:18:28: undefined: unix.SYS_IOCTL
vendor/github.com/docker/docker/pkg/term/termios_bsd.go:24:31: undefined: unix.SYS_IOCTL
vendor/github.com/docker/docker/pkg/term/termios_bsd.go:37:31: undefined: unix.SYS_IOCTL

Signed-off-by: Gyuho Lee <leegyuho@amazon.com>

* vendor: update golang/sys/unix

Signed-off-by: Gyuho Lee <leegyuho@amazon.com>

* CHANGELOG: update

Signed-off-by: Gyuho Lee <leegyuho@amazon.com>

* eks: ignore Sync errors

Signed-off-by: Gyuho Lee <leegyuho@amazon.com>